import { pageMetadata } from "../../lib/site";
import Link from "next/link";
import { LegalNavigation } from "../legal-navigation";

export const metadata = pageMetadata("Marketplace Partner Agreement", "Payment, payout and customer obligations for Tivorah organisers, providers and sellers.", "/marketplace-partner-agreement");

export default function MarketplacePartnerAgreement() {
  return <article className="content">
    <span className="eyebrow">Organisers, providers &amp; sellers</span>
    <h1>Marketplace Partner Agreement</h1>
    <p className="legal-meta"><strong>Version 1.0 · Last updated:</strong> 7 October 2026</p>
    <div className="legal-callout"><strong>The short version</strong><p>When you accept an in-app payment for your item, service or event, you supply it directly to the customer. Tivorah provides listing, booking, ticketing and payment-facilitation tools and charges the platform fee disclosed at checkout. Stripe Connect Express processes payments and payouts.</p></div>

    <p>This Marketplace Partner Agreement is between TIVORAH PTY LTD (ABN 94 702 094 844) and each organiser, service provider or seller using Tivorah&apos;s paid transaction features (a <strong>Partner</strong>). It forms part of the <Link href="/terms">Terms of Use</Link>. For a paid transaction, this Agreement prevails over inconsistent general wording in the Terms.</p>

    <h2>1. Acceptance and authority</h2>
    <p>You accept this Agreement when you connect Stripe Connect Express, activate an in-app paid feature, or submit a paid event, service or item for sale. If you act for a business, association or other entity, you confirm you have authority to bind it. You must be at least 18 and legally able to enter this Agreement.</p>

    <h2>2. Our role and your role</h2>
    <p>Tivorah provides technology for discovery, listings, bookings, digital tickets, QR validation, communications and payment facilitation. Unless a checkout expressly identifies Tivorah as the supplier, the Partner is the seller and supplier of the item, service or event and the customer&apos;s contract for that supply is with the Partner.</p>
    <p>You authorise Tivorah to facilitate payments, receipts and refunds for your transactions as described in this Agreement. This authority does not extend to running your business or determining your tax position, and does not create employment, a partnership or a franchise. Stripe processes payments under its own terms; using Stripe does not remove either party’s obligations under applicable law.</p>

    <h2>3. Stripe onboarding and payouts</h2>
    <ul><li>You must complete and maintain Stripe Connect Express onboarding and give Stripe accurate identity, ownership, business, tax and bank information.</li><li>Stripe performs its own verification and may delay, restrict or stop charges or payouts. Tivorah may disable paid features when required information, capabilities or risk checks are incomplete.</li><li>Stripe directs the applicable net amount to your connected balance and pays it to your nominated bank account under the payout schedule and any reserve, delay or restriction shown by Stripe or Tivorah.</li><li>Tivorah does not receive your full card number or online-banking credentials. Manage bank details and verification through Stripe.</li></ul>

    <p>Online receipt of customer payments for events and services is currently available only to Partners whose seller business is established in Australia. You must accurately declare your business country and meet Tivorah’s onboarding requirements and Stripe’s account requirements. Australian business eligibility does not guarantee approval or determine tax liability. A customer’s location, your nationality, device location or payment currency does not replace your business country.</p>
    <p>Members outside Australia may use supported features that do not involve receiving payment through Tivorah, including Hubs, listings, enquiries and non-payment bookings. Creating an account or publishing a listing does not authorise online payment collection. Any expansion of seller payment availability will be announced separately. A payment-country restriction does not by itself close your account or remove access to existing transaction records; existing customer, refund and dispute obligations continue.</p>

    <h2>4. Prices and platform fees</h2>
    <p>You set the underlying listing price. Tivorah may set different percentage and fixed platform fees for items, services and events and may configure the fee to be paid by the customer or deducted from Partner proceeds. The applicable fee, payer and total must be shown before the customer confirms payment. When you advertise a price, include every compulsory fee or charge that a customer must pay (other than optional extras and delivery costs shown separately), so the total price is clear from the start. Each completed checkout keeps its original fee snapshot even if Tivorah later changes pricing.</p>
    <p>Stripe processing, dispute, currency-conversion or payout fees may also apply under Stripe&apos;s terms. Tivorah will give you at least 14 days&apos; notice of an increase in platform fees that affects your future transactions. A new fee does not retrospectively change a completed order.</p>

    <h2>5. Partner obligations</h2>
    <ul><li>Describe price, availability, condition, inclusions, exclusions, location, dates, accessibility and material risks accurately.</li><li>Hold every licence, permit, registration, qualification, venue approval and insurance required for your supply.</li><li>Deliver each valid paid booking or ticket and do not oversell, substitute or materially change it without lawful notice and remedies.</li><li>Comply with the Australian Consumer Law, tax law, safety, privacy, anti-discrimination, intellectual-property and industry-specific requirements.</li><li>Do not use paid features for illegal, unsafe, deceptive, counterfeit, stolen, sanctioned or prohibited activity.</li><li>Keep evidence of fulfilment, attendance, delivery, communications, policies and refunds for disputes and legal compliance.</li><li>For events, do not allow or encourage tickets to be resold above their original price or through automated buying tools, and follow any state or territory ticket-resale law and venue conditions that apply.</li><li>Use only photos, videos, music, trade marks and text in your listings and shop that you own or are licensed to use.</li></ul>

    <h2>6. Cancellations, refunds and chargebacks</h2>
    <p>You must publish and honour a clear cancellation and refund policy that does not exclude non-excludable rights. If you cancel, fail to supply, or materially change an event or service, you must promptly notify affected customers and provide every refund or other remedy required by law.</p>
    <p>You authorise Tivorah to facilitate refunds through Stripe where you request them or where Tivorah reasonably considers a refund necessary to comply with law, protect a customer, remedy non-supply or manage platform risk. Refunds may reverse transfers and platform fees where configured or legally required. You remain responsible for liabilities arising from your supply, including refunds, chargebacks, dispute fees and negative balances, to the extent permitted by law.</p>
    <p>You authorise Tivorah and Stripe to use and share relevant listing, booking, ticket, check-in, communication, refund and fulfilment records to prevent fraud and respond to a payment dispute. Excessive disputes, unresolved refunds or suspected fraud may result in delayed payouts, listing removal or suspension.</p>

    <h2>7. Customer and attendee information</h2>
    <p>Use customer information only to provide, support, verify or refund the relevant transaction unless the person gives separate valid marketing consent. Keep it secure, limit staff access, do not scrape or sell it, delete it when no longer lawfully needed, and notify Tivorah promptly of a suspected breach. A ticket QR or booking credential must not be copied, published or used for tracking unrelated activity.</p>

    <h2>8. Tax and records</h2>
    <p>You are responsible for determining and meeting your GST, income-tax, invoicing, return-filing and tax-payment obligations for your independent supplies. Tivorah may collect, retain and report identity and transaction information where required under the Sharing Economy Reporting Regime or another law. This may include your legal name, date of birth, ABN, address, bank or payout account identifiers and the amounts you received. You must give us accurate information when asked, and we may pause paid features until we have what the law requires. Amounts shown in Tivorah or Stripe are not tax advice.</p>

    <p>Tivorah remains responsible for taxes on its own supplies and any collection, reporting or other obligations imposed on it by law. Payment facilitation does not transfer your tax obligations to Tivorah. Nothing in this Agreement shifts a statutory liability contrary to law.</p>
    <p>You must keep your seller tax declaration accurate and update it when your registration changes. A shared declaration can be used for your events and services, but the tax treatment of an individual offering may require separate information. Stripe identity verification and an ABN format check do not establish GST registration or the correct tax treatment. Unless expressly agreed separately, payment processing does not include tax registration, return preparation, filing or remittance on your behalf.</p>
    <p>Any GST identified as included in a price is part of that price, not an additional deduction from the customer. Seller GST and tax on Tivorah’s fees are separate. Reporting information to the ATO does not discharge your own return or payment obligations. Read <Link href="/seller-tax">Seller taxes and reporting</Link> for the current product capabilities and where to update your details.</p>

    <h2>9. Suspension and risk controls</h2>
    <p>Tivorah may restrict a listing, payment, payout or Partner account where reasonably necessary for safety, fraud prevention, sanctions compliance, an investigation, a Stripe restriction, excessive disputes, breach of this Agreement or legal compliance. Where lawful and practical, Tivorah will explain the action and provide a review path. Existing customer obligations survive suspension.</p>

    <h2>10. Indemnity and liability</h2>
    <p>To the extent permitted by law, you are responsible for, and will reimburse Tivorah for, reasonable losses, claims and costs to the extent they are caused by your item, service or event; your breach of law or this Agreement; injury, property damage or non-supply; refunds or chargebacks you are responsible for; infringement by your content; or your misuse of customer information. Your responsibility is reduced to the extent a loss was caused or contributed to by Tivorah&apos;s negligence, unlawful conduct or breach. Tivorah will tell you promptly about a claim and give you a fair opportunity to respond.</p>
    <p>Nothing excludes a guarantee, right or remedy that cannot lawfully be excluded. Subject to those rights, Tivorah is not liable for indirect or consequential loss caused by an independent Partner or third-party service. Tivorah is responsible for losses caused by its own breach of this Agreement, negligence or unlawful conduct. Except for liability that cannot be limited by law, or that arises from Tivorah&apos;s fraud, wilful misconduct, misuse of your information, or failure to pass on money that Stripe has paid to Tivorah for you, Tivorah&apos;s total liability to a Partner relating to paid marketplace facilitation is limited to the greater of the platform fees paid by that Partner during the preceding 12 months and A$1,000.</p>

    <h2>11. Changes, termination and contact</h2>
    <p>Tivorah may update this Agreement only for genuine product, risk, legal or operational reasons. We will give you at least 14 days&apos; notice in the app or by email before a change that materially reduces your rights or increases your obligations takes effect, unless a shorter period is needed to comply with law, a payment-network or Stripe requirement, or to address a serious safety or fraud risk. Changes never apply retrospectively to completed transactions.</p>
    <p>If you do not agree to a change, you may stop offering new paid transactions and disconnect Stripe before it takes effect, without any fee or penalty from Tivorah. You may end this Agreement at any time in the same way. Existing customer, refund, tax, privacy and dispute obligations continue for transactions already made.</p>
    <p>This Agreement is governed by South Australian and applicable Commonwealth law. Questions can be sent to <a href="mailto:support@tivorah.com">support@tivorah.com</a>.</p>
    <LegalNavigation />
  </article>;
}
