"use client";

import { usePathname, useSearchParams } from "next/navigation";
import { PayoutsLoading } from "../business/payouts-layout";
import { LoadingState } from "../ui/loading-state";
import { MessageThreadLoading } from "./message-thread-loading";
import { ShopSkeleton } from "../shop/shop-view";
import { BusinessFormSkeleton } from "../business/form-skeleton";
import { BusinessOverviewSkeleton } from "../business/overview";

const bar = (name: string) => <span className={`${name} tivorah-shimmer`} />;

export function AccountSurfaceLoading({ embedded = false, route }: { embedded?: boolean; route?: string }) {
  const currentPath = usePathname();
  const searchParams = useSearchParams();
  const path = route ?? currentPath;
  if (path === "/business/payouts") return <PayoutsLoading />;
  if (path === "/business/showcase/preview") return <ShopSkeleton />;
  const dashboard = path === "/account";
  const tickets = path === "/account/tickets";
  const bookings = path === "/account/bookings";
  const messages = path === "/account/messages";
  const thread = path.startsWith("/account/messages/");
  const business = path.startsWith("/business");
  const title = business ? "Your business on Tivorah" : tickets ? "Your tickets" : bookings ? "Service appointments" : path.includes("messages") ? "Messages" : path.includes("notifications") ? "Updates" : "Your account";
  const wrapper = `${embedded ? "" : "product-page page-shell "}account-surface-loading`;
  if (dashboard) return <div className={`${wrapper} account-dashboard-loading`} role="status" aria-busy="true" aria-label="Loading your account">
    <header className="account-heading" aria-hidden="true"><div className="account-dashboard-loading-intro">{bar("account-loading-eyebrow")}{bar("account-loading-title")}{bar("account-loading-summary")}</div>{bar("account-loading-signout")}</header>
    <section className="account-panel account-create-panel account-create-loading" aria-hidden="true"><div>{bar("account-loading-create-title")}</div><div className="account-create-options">{Array.from({ length: 3 }, (_, index) => <div key={index}>{bar("account-loading-option-title")}{bar("account-loading-option-copy")}</div>)}</div></section>
    <div className="account-grid" aria-hidden="true">{Array.from({ length: 4 }, (_, index) => <section className="account-panel account-loading-card" key={index}>{bar("account-loading-card-title")}<div className="account-loading-card-copy">{bar("")}{bar("")}</div>{index === 3 ? <div className="account-loading-links">{Array.from({ length: 4 }, (_, link) => <span className="tivorah-shimmer" key={link} />)}</div> : bar("account-loading-card-action")}</section>)}</div>
  </div>;
  if (tickets || bookings) return <div className={`${wrapper} account-collection-loading`} role="status" aria-busy="true" aria-label={`Loading ${title.toLowerCase()}`}><div className="account-loading-breadcrumb" aria-hidden="true">{bar("short")}{bar("tiny")}</div><header className="account-ticket-heading" aria-hidden="true"><div>{bar("account-loading-eyebrow")}{bar("account-loading-title")}{bar("account-loading-summary")}</div></header>{bookings ? <div className="account-loading-tabs" aria-hidden="true">{bar("")}{bar("")}</div> : null}<div className="account-ticket-layout" aria-hidden="true"><section className="account-ticket-list">{bar("account-loading-section-title")}{Array.from({ length: 3 }, (_, index) => <div className="account-loading-ticket-row" key={index}>{bar("account-loading-date")}<div>{bar("account-loading-row-title")}{bar("account-loading-row-copy")}</div>{bar("account-loading-status")}</div>)}</section><section className="account-ticket-preview">{bar("account-loading-preview-label")}<div className="account-loading-preview-card">{bar("account-loading-preview-band")}<div>{bar("account-loading-preview-title")}{bar("account-loading-preview-copy")}{bar("account-loading-preview-copy short")}{bar("account-loading-preview-divider")}{bar("account-loading-preview-copy")}{bar("account-loading-preview-button")}</div></div></section></div></div>;
  // A conversation loads into the same shape as the real thread (heading, bubbles, reply bar).
  if (thread) return embedded ? <MessageThreadLoading /> : <div className="product-page page-shell message-workspace message-thread-page"><MessageThreadLoading /></div>;
  if (messages || thread) return <div className={`${wrapper} account-message-loading`} role="status" aria-busy="true" aria-label={`Loading ${title.toLowerCase()}`}><div className="account-loading-breadcrumb" aria-hidden="true">{bar("short")}{bar("tiny")}</div><header aria-hidden="true">{bar("account-loading-eyebrow")}{bar("account-loading-title")}{bar("account-loading-summary")}</header>{thread ? <div className="account-loading-thread" aria-hidden="true">{bar("account-loading-thread-topic")}{bar("account-loading-bubble mine")}{bar("account-loading-bubble")}{bar("account-loading-compose")}</div> : <div className="account-loading-inbox" aria-hidden="true">{Array.from({ length: 3 }, (_, index) => <div key={index}>{bar("account-loading-avatar")}<section>{bar("account-loading-row-title")}{bar("account-loading-row-copy")}</section></div>)}</div>}</div>;
  if (path === "/business/showcase") return <BusinessFormSkeleton shop />;
  if (path === "/business/create") return <BusinessFormSkeleton />;
  if (path.startsWith("/business/listings/")) return <div className={`${wrapper} business-form-loading`} role="status" aria-busy="true" aria-label="Loading business form"><section className="product-form business-create" aria-hidden="true">{bar("business-form-eyebrow")}{bar("business-form-title")}<div className="business-form-fields">{bar("business-form-field")}{bar("business-form-divider")}{bar("business-form-heading")}{bar("business-form-field")}{bar("business-form-field")}{bar("business-form-wide")}{bar("business-form-field")}</div></section></div>;
  if (path.startsWith("/business/events/")) return <div className={`${wrapper} event-manage business-event-loading`} role="status" aria-busy="true" aria-label="Loading event workspace"><div className="account-loading-breadcrumb" aria-hidden="true">{bar("short")}{bar("tiny")}</div><header className="event-manage-header" aria-hidden="true"><div>{bar("business-form-eyebrow")}{bar("business-form-title")}{bar("account-loading-summary")}</div>{bar("event-loading-publish")}</header><div className="business-event-loading-tabs" aria-hidden="true">{Array.from({ length: 5 }, (_, index) => <span className="tivorah-shimmer" key={index} />)}</div><div className="event-manage-content"><section className="product-form" aria-hidden="true">{bar("business-form-heading")}{bar("business-form-field")}{bar("business-form-field")}{bar("business-form-wide")}{bar("business-form-heading")}{bar("business-form-field")}{bar("business-form-field")}</section></div></div>;
  if (path === "/business") return <div className={`${wrapper} business-workspace-loading`} role="status" aria-busy="true" aria-label="Loading your business"><BusinessOverviewSkeleton /><div className="business-section" aria-hidden="true">{bar("account-loading-section-title")}<div className="business-board"><div className="business-list">{Array.from({ length: 5 }, (_, index) => <div className="business-list-row" key={index}>{bar("account-loading-avatar")}<div>{bar("account-loading-row-title")}{bar("account-loading-row-copy")}</div></div>)}</div><div className="business-preview-wrap">{bar("account-loading-preview-label")}<div className="business-preview">{bar("account-loading-preview-band")}{bar("account-loading-preview-title")}{bar("account-loading-preview-copy")}<div className="business-event-summary-loading">{Array.from({ length: searchParams.get("view") === "events" ? 4 : 2 }, (_, index) => <span className="tivorah-shimmer" key={index} />)}</div>{bar("account-loading-preview-button")}</div></div></div></div></div>;
  return <div className={wrapper} role="status" aria-busy="true" aria-label={`Loading ${title.toLowerCase()}`}><header className="account-heading"><div><p className="product-eyebrow">{business ? "MADE BY YOU" : "YOUR TIVORAH"}</p><h1>{title}</h1></div></header>{business ? <><div className="account-loading-section">{bar("account-loading-heading")}<LoadingState label="Loading your listings…" variant="panels" count={2} /></div><div className="account-loading-section">{bar("account-loading-heading")}<LoadingState label="Loading your events…" variant="panels" count={2} /></div></> : <LoadingState label="Loading your account…" variant={path.includes("settings") ? "form" : "list"} count={3} />}</div>;
}
