'use client';
import { useState } from 'react';
export type FeatureFlag = { id: number; key: string; name: string; description?: string; enabled: boolean; presentation: 'hidden' | 'coming_soon' | 'maintenance'; version: number; environment?: string; platforms?: string[]; effectiveAt?: string | null; config?: { group?: string } };
const states = { enabled: 'Available', hidden: 'Hidden', coming_soon: 'Coming soon', maintenance: 'Maintenance' };
const paymentFeatureKeys = new Set(['paid_tickets', 'checkout', 'service_payments']);
export default function FeatureManager({ flags, loading, busy, update, history, toggleHistory }: { flags: FeatureFlag[]; loading: boolean; busy: number | null; update: (flag: FeatureFlag, patch: Partial<FeatureFlag>) => Promise<void>; history: Record<number, any[]>; toggleHistory: (flag: FeatureFlag) => Promise<void> }) {
  const [search, setSearch] = useState(''), [filter, setFilter] = useState('all');
  const groups = flags.filter(flag => `${flag.name} ${flag.key} ${flag.description || ''}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || (flag.enabled ? 'enabled' : flag.presentation) === filter)).reduce<Record<string, FeatureFlag[]>>((all, flag) => { (all[flag.config?.group || 'Other features'] ??= []).push(flag); return all; }, {});
  return <section className="admin-settings feature-workspace"><div className="workspace-intro"><div><span className="panel-kicker">App availability</span><h2>Feature controls</h2><p>Choose whether people can use a feature and what they see when it is unavailable.</p></div></div>
    <div className="feature-summary"><div><strong>{flags.filter(flag => flag.enabled).length}</strong><span>Available</span></div><div><strong>{flags.filter(flag => !flag.enabled).length}</strong><span>Unavailable</span></div><div><strong>{flags[0]?.environment || 'Current'}</strong><span>Environment</span></div></div>
    <div className="workspace-filters"><label>Find a feature<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search features" type="search" /></label><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All states</option>{Object.entries(states).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
    {loading && !flags.length ? <p role="status">Loading features…</p> : !Object.keys(groups).length ? <div className="workspace-empty"><h3>{flags.length ? 'No matching features' : 'No features configured'}</h3><p>{flags.length ? 'Try another search or state.' : 'Refresh to check this environment again.'}</p></div> : Object.entries(groups).map(([group, rows]) => <section key={group} className="feature-group-panel"><h3>{group.replaceAll('_', ' ')}</h3><div className="feature-card-grid">{rows.map(flag => <article key={flag.id} className="feature-control-card" aria-busy={busy === flag.id}><div className="feature-card-heading"><h4>{flag.name}</h4><span className={`workspace-status ${flag.enabled ? 'is-on' : ''}`}>{states[flag.enabled ? 'enabled' : flag.presentation]}</span></div>{flag.description ? <p>{flag.description}</p> : null}<label>Availability<select disabled={busy !== null || loading} value={flag.enabled ? 'enabled' : flag.presentation} onChange={e => void update(flag, e.target.value === 'enabled' ? { enabled: true } : { enabled: false, presentation: e.target.value as FeatureFlag['presentation'] })}>{Object.entries(states).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><p className="feature-state-explanation">{flag.enabled ? 'People can use this feature on its configured platforms.' : flag.presentation === 'hidden' ? 'Removed from navigation; API access is blocked.' : flag.presentation === 'coming_soon' ? 'Shows a coming-soon message; access is blocked.' : 'Shows a maintenance message; access is blocked.'}</p>{paymentFeatureKeys.has(flag.key) ? <p className="feature-state-explanation">This is a payment feature. Toggling it also hides its fee row on connected sellers' Payouts screen and sends them a one-time notice they must acknowledge on next login.</p> : null}<details><summary>Details and change history</summary><p>Platforms: {flag.platforms?.join(', ') || 'Configured platforms'}<br />Key: {flag.key}<br />Version: {flag.version}{flag.effectiveAt ? <><br />Effective from: {new Date(flag.effectiveAt).toLocaleString()}</> : null}</p><button className="admin-secondary" onClick={() => void toggleHistory(flag)}>Load history</button>{history[flag.id]?.map(row => <p key={row.id}>v{row.version} · {row.action} · {new Date(row.createdAt).toLocaleString()}</p>)}</details></article>)}</div></section>)}
  </section>;
}
