"use client";
import { FormEvent, useEffect, useState } from "react";
import "./admin.css";

type Flag={id:number;key:string;name:string;enabled:boolean;presentation:"hidden"|"coming_soon"|"maintenance";version:number;config?:{group?:string}};
type Dashboard={totals:Record<string,number>;health:Record<string,string>};
type User={id:number;username:string;email:string;role:string;isActive:boolean;firstName?:string;lastName?:string};
type Report={id:number;targetType:string;targetId:string;reason:string;details?:string;status:string};
type Broadcast={id:number;title:string;category:string;status:string;recipientCount:number;deliveredCount:number;failedCount:number;createdAt:string};
type Delivery={id:number;status:string;errorCode?:string;errorMessage?:string;attemptedAt:string};
type Template={id:number;key:string;name:string;category:string;title:string;body:string;active:boolean};
type Section="overview"|"features"|"users"|"moderation"|"jobs"|"notifications";
const API=process.env.NEXT_PUBLIC_API_URL??"";

export default function AdminPage(){
 const[token,setToken]=useState("");const[section,setSection]=useState<Section>("overview");const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[features,setFeatures]=useState<Flag[]>([]);const[users,setUsers]=useState<User[]>([]);const[reports,setReports]=useState<Report[]>([]);const[error,setError]=useState("");
 const[mfaChallenge,setMfaChallenge]=useState("");const[enrollment,setEnrollment]=useState<{secret:string;otpauthUri:string}|null>(null);const[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);
 const[broadcasts,setBroadcasts]=useState<Broadcast[]>([]);const[deliveries,setDeliveries]=useState<Delivery[]>([]);
 const[templates,setTemplates]=useState<Template[]>([]);
 const[jobs,setJobs]=useState<any[]>([]);const[applications,setApplications]=useState<any[]>([]);const[documentAccess,setDocumentAccess]=useState<any[]>([]);
 const[featureSearch,setFeatureSearch]=useState("");const[featureBusy,setFeatureBusy]=useState<number|null>(null);const[featureHistory,setFeatureHistory]=useState<Record<number,any[]>>({});
 // Initial session restore intentionally runs once; load is defined in component scope.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const saved=sessionStorage.getItem("tivorah_admin_token")??"";setToken(saved);if(saved)void load(saved)},[]);
 async function request(path:string,init:RequestInit={},auth=token){const response=await fetch(`${API}${path}`,{...init,headers:{"content-type":"application/json",authorization:`Bearer ${auth}`,...init.headers}});const json=response.status===204?{}:await response.json();if(!response.ok)throw new Error(json.message??"Request failed");return json.data}
 async function load(auth=token){try{setError("");const[d,f,u,r,b,p,t,j,a,x]=await Promise.all([request("/api/v1/admin/dashboard",{},auth),request("/api/v1/admin/features",{},auth),request("/api/v1/admin/users",{},auth),request("/api/v1/admin/reports",{},auth),request("/api/v1/admin/broadcasts",{},auth),request("/api/v1/admin/push-deliveries",{},auth),request("/api/v1/admin/notification-templates",{},auth),request("/api/v1/admin/jobs",{},auth),request("/api/v1/admin/job-applications",{},auth),request("/api/v1/admin/job-document-access",{},auth)]);setDashboard(d);setFeatures(f);setUsers(u);setReports(r);setBroadcasts(b);setDeliveries(p);setTemplates(t);setJobs(j.jobs??[]);setApplications(a.applications??[]);setDocumentAccess(x.access??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{setError("");const response=await fetch(`${API}/api/auth/signin`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userIdentity:form.get("email"),password:form.get("password")})});const body=await response.json();if(!response.ok)throw new Error(body.message??"Sign in failed");if(body.data?.mfaRequired){setMfaChallenge(body.data.challengeToken);return}const value=body.data?.token;if(!value)throw new Error("The API did not return an access token");if(body.data?.mfaEnrollmentRequired){setToken(value);const setup=await request("/api/auth/mfa/enroll",{method:"POST"},value);setEnrollment(setup);return}sessionStorage.setItem("tivorah_admin_token",value);setToken(value);await load(value)}catch(e){setError(e instanceof Error?e.message:"Sign in failed")}}
 async function verifyMfa(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{setError("");const response=await fetch(`${API}/api/auth/mfa/verify`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeToken:mfaChallenge,code:form.get("code")})});const body=await response.json();if(!response.ok)throw new Error(body.message??"MFA verification failed");const value=body.data.token;sessionStorage.setItem("tivorah_admin_token",value);setMfaChallenge("");setToken(value);await load(value)}catch(e){setError(e instanceof Error?e.message:"MFA verification failed")}}
 async function confirmEnrollment(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{const data=await request("/api/auth/mfa/confirm",{method:"POST",body:JSON.stringify({code:form.get("code")})},token);setRecoveryCodes(data.recoveryCodes);setEnrollment(null);setToken("")}catch(e){setError(e instanceof Error?e.message:"MFA enrollment failed")}}
 async function updateFlag(flag:Flag,patch:Partial<Flag>){if(!window.confirm(`${patch.enabled===true?'Enable':patch.enabled===false?'Disable':'Change'} ${flag.name}? The mobile app and API will update after publishing.`))return;try{setFeatureBusy(flag.id);setError("");const updated=await request(`/api/v1/admin/features/${flag.id}`,{method:"PATCH",body:JSON.stringify(patch)});setFeatures(all=>all.map(item=>item.id===flag.id?updated:item))}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setFeatureBusy(null)}}
 async function publishFlag(flag:Flag){try{setFeatureBusy(flag.id);await request(`/api/v1/admin/features/${flag.id}/publish`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Publish failed")}finally{setFeatureBusy(null)}}
 async function toggleHistory(flag:Flag){if(featureHistory[flag.id]){setFeatureHistory(all=>({...all,[flag.id]:[]}));return}try{const rows=await request(`/api/v1/admin/features/${flag.id}/history`);setFeatureHistory(all=>({...all,[flag.id]:rows}))}catch(e){setError(e instanceof Error?e.message:"History failed")}}
 async function updateUser(user:User,patch:Partial<User>){try{const updated=await request(`/api/v1/admin/users/${user.id}/access`,{method:"PATCH",body:JSON.stringify(patch)});setUsers(all=>all.map(item=>item.id===user.id?{...item,...updated}:item))}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
 async function updateReport(report:Report,status:string){try{const updated=await request(`/api/v1/admin/reports/${report.id}`,{method:"PATCH",body:JSON.stringify({status})});setReports(all=>all.map(item=>item.id===report.id?updated:item))}catch(e){setError(e instanceof Error?e.message:"Update failed")}}
 async function createBroadcast(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{await request('/api/v1/admin/broadcasts',{method:'POST',body:JSON.stringify({title:form.get('title'),body:form.get('body'),category:form.get('category'),deepLink:form.get('deepLink')||undefined,targetRoles:form.getAll('roles')})});e.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Broadcast was not queued')}}
 async function saveTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{await request('/api/v1/admin/notification-templates',{method:'POST',body:JSON.stringify({key:form.get('key'),name:form.get('name'),category:form.get('category'),title:form.get('title'),body:form.get('body'),deepLink:form.get('deepLink')||undefined,active:true})});e.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Template was not saved')}}
 const groupedFeatures=features.filter(flag=>`${flag.name} ${flag.key}`.toLowerCase().includes(featureSearch.toLowerCase())).reduce<Record<string,Flag[]>>((groups,flag)=>{const group=flag.config?.group??"Other";(groups[group]??=[]).push(flag);return groups},{});
 if(recoveryCodes.length)return <main className="admin"><div className="content"><h1>Save your recovery codes</h1><section className="panel"><p>Each code works once. Store them in a password manager; they will not be shown again.</p><pre>{recoveryCodes.join("\n")}</pre><button onClick={()=>setRecoveryCodes([])}>I have saved them — sign in</button></section></div></main>;
 if(mfaChallenge)return <main className="admin"><div className="content"><span className="eyebrow">Staff verification</span><h1>Enter your MFA code</h1><form className="panel" onSubmit={verifyMfa}><p><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9A-Fa-f-]{6,20}" placeholder="6-digit code or recovery code" required/></p><button>Verify and continue</button>{error&&<p className="error">{error}</p>}</form></div></main>;
 if(enrollment)return <main className="admin"><div className="content"><span className="eyebrow">Required security setup</span><h1>Enable multi-factor authentication</h1><form className="panel" onSubmit={confirmEnrollment}><p>Add this secret to Google Authenticator, Microsoft Authenticator, 1Password, or another TOTP app:</p><pre>{enrollment.secret}</pre><p><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" placeholder="6-digit code" required/></p><button>Confirm MFA</button>{error&&<p className="error">{error}</p>}</form></div></main>;
 if(!token)return <main className="admin"><div className="content"><span className="eyebrow">Staff only</span><h1>Admin sign in</h1><form className="panel" onSubmit={login}><p><input name="email" type="email" placeholder="Admin email" required/></p><p><input name="password" type="password" placeholder="Password" required/></p><button>Sign in</button>{error&&<p className="error">{error}</p>}</form></div></main>;
 return <main className="admin"><div className="admin-shell"><div className="admin-head"><div><span className="eyebrow">Operations</span><h2>Tivorah dashboard</h2></div><button onClick={()=>{sessionStorage.removeItem("tivorah_admin_token");setToken("")}}>Sign out</button></div><nav className="admin-tabs">{(["overview","features","users","moderation","jobs","notifications"]as Section[]).map(item=><button className={section===item?"active":""} key={item} onClick={()=>setSection(item)}>{item}</button>)}<button onClick={()=>load()}>Refresh</button></nav>{error&&<p className="error">{error}</p>}
 {section==="overview"&&<><section className="cards">{Object.entries(dashboard?.totals??{}).map(([key,value])=><div className="card" key={key}><span>{key.replaceAll("_"," ")}</span><strong>{value.toLocaleString()}</strong></div>)}</section><section className="panel"><h3>System health</h3>{Object.entries(dashboard?.health??{}).map(([key,value])=><p key={key}><strong>{key}</strong>: {value}</p>)}</section></>}
 {section==="features"&&<section className="panel"><h3>Feature controls</h3><p>Changes are enforced by both the API and mobile navigation. Review, then publish.</p><input className="feature-search" value={featureSearch} onChange={e=>setFeatureSearch(e.target.value)} placeholder="Search feature name or key"/>{features.length===0?<p>No feature flags have been seeded yet.</p>:Object.entries(groupedFeatures).map(([group,flags])=><div key={group}><h4 className="feature-group">{group}</h4>{flags.map(flag=><div key={flag.id}><div className="feature"><div><strong>{flag.name}</strong><small><br/>{flag.key} · v{flag.version}</small></div><label><input disabled={featureBusy===flag.id} type="checkbox" checked={flag.enabled} onChange={e=>updateFlag(flag,{enabled:e.target.checked})}/> Enabled</label><select disabled={featureBusy===flag.id} value={flag.presentation} onChange={e=>updateFlag(flag,{presentation:e.target.value as Flag["presentation"]})}><option value="hidden">Hidden</option><option value="coming_soon">Coming soon</option><option value="maintenance">Maintenance</option></select><span><button disabled={featureBusy===flag.id} onClick={()=>publishFlag(flag)}>{featureBusy===flag.id?'Saving…':'Publish'}</button> <button onClick={()=>toggleHistory(flag)}>History</button></span></div>{featureHistory[flag.id]?.length?<div className="feature-history">{featureHistory[flag.id].slice(0,8).map(row=><small key={row.id}>v{row.version} · {row.action} · {new Date(row.createdAt).toLocaleString()}<br/></small>)}</div>:null}</div>)}</div>)}</section>}
 {section==="users"&&<section className="panel"><h3>User access</h3>{users.map(user=><div className="feature" key={user.id}><div><strong>{user.firstName} {user.lastName}</strong><small><br/>{user.email} · @{user.username}</small></div><select value={user.role} onChange={e=>updateUser(user,{role:e.target.value})}>{["user","tester","moderator","support","finance","event_operations","analyst","admin","owner"].map(role=><option key={role}>{role}</option>)}</select><span>{user.isActive?"Active":"Suspended"}</span><button onClick={()=>updateUser(user,{isActive:!user.isActive})}>{user.isActive?"Suspend":"Restore"}</button></div>)}</section>}
 {section==="moderation"&&<section className="panel"><h3>Moderation queue</h3>{reports.length===0?<p>No open reports.</p>:reports.map(report=><div className="feature" key={report.id}><div><strong>{report.reason}</strong><small><br/>{report.targetType} #{report.targetId} · {report.details}</small></div><span>{report.status}</span><button onClick={()=>updateReport(report,"reviewing")}>Review</button><button onClick={()=>updateReport(report,"resolved")}>Resolve</button></div>)}</section>}
 {section==="jobs"&&<><section className="panel"><h3>Job listings</h3>{jobs.map(job=><div className="feature" key={job.id}><div><strong>{job.title}</strong><small><br/>{job.companyName} · {job.location}</small></div><span>{job.status}</span><small>{new Date(job.updatedAt).toLocaleString()}</small></div>)}</section><section className="panel"><h3>Applications</h3>{applications.map(row=><div className="feature" key={row.application.id}><div><strong>{row.jobTitle}</strong><small><br/>@{row.applicantUsername} · {row.documentName||"No document"}</small></div><span>{row.application.status}</span></div>)}</section><section className="panel"><h3>Protected document access</h3><p>Every granted and denied CV access is retained for incident review.</p>{documentAccess.map(row=><div className="feature" key={row.access.id}><div><strong>{row.documentName}</strong><small><br/>@{row.accessorUsername} · {row.access.purpose}</small></div><span>{row.access.granted?"Granted":"Denied"}</span><small>{new Date(row.access.createdAt).toLocaleString()}</small></div>)}</section></>}
 {section==="notifications"&&<><section className="panel"><h3>Notification template</h3><form onSubmit={saveTemplate}><p><input name="key" placeholder="Key, e.g. order.shipped" pattern="[a-z0-9_.-]+" required/> <input name="name" placeholder="Template name" required/></p><p><select name="category">{['activity','chat','communities','events','jobs','marketplace','safety','marketing'].map(value=><option key={value}>{value}</option>)}</select></p><p><input name="title" placeholder="Title" required/></p><p><textarea name="body" placeholder="Message body" required/></p><p><input name="deepLink" placeholder="Optional internal path"/></p><button>Save template</button></form>{templates.map(item=><div className="feature" key={item.id}><div><strong>{item.name}</strong><small><br/>{item.key} · {item.category}</small></div><span>{item.active?'Active':'Inactive'}</span></div>)}</section><section className="panel"><h3>Queue broadcast</h3><form onSubmit={createBroadcast}><p><input name="title" placeholder="Notification title" maxLength={100} required/></p><p><textarea name="body" placeholder="Message" maxLength={1000} required/></p><p><select name="category" defaultValue="activity">{['activity','chat','communities','events','jobs','marketplace','safety','marketing'].map(value=><option key={value}>{value}</option>)}</select></p><p><input name="deepLink" placeholder="Optional internal path, e.g. /notifications/notifications"/></p><fieldset><legend>Audience (none means all active users)</legend>{['user','tester','moderator','support','finance','event_operations','analyst','admin','owner'].map(role=><label key={role}><input type="checkbox" name="roles" value={role}/> {role} </label>)}</fieldset><button>Queue broadcast</button></form></section><section className="panel"><h3>Broadcast history</h3>{broadcasts.map(item=><div className="feature" key={item.id}><div><strong>{item.title}</strong><small><br/>{item.category} · {new Date(item.createdAt).toLocaleString()}</small></div><span>{item.status}</span><span>{item.deliveredCount}/{item.recipientCount} devices · {item.failedCount} failed</span></div>)}</section><section className="panel"><h3>Recent delivery attempts</h3>{deliveries.slice(0,50).map(item=><div className="feature" key={item.id}><span>{item.status}</span><small>{item.errorCode} {item.errorMessage}</small><small>{new Date(item.attemptedAt).toLocaleString()}</small></div>)}</section></>}
 </div></main>;
}
