'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
type Feature = 'item' | 'service' | 'event';
type Rule = { id: number; feature: Feature; collectionMethod: 'transaction' | 'subscription'; itemCondition: string; category: string; billingInterval: 'month' | 'year'; subscriptionCents: number; percentageBps: number; fixedFeeCents: number; chargedTo: 'buyer' | 'provider'; active: boolean; version: number };
const features: { key: Feature; title: string; description: string }[] = [{ key: 'item', title: 'Items', description: 'Set rates by item condition and category.' }, { key: 'service', title: 'Services', description: 'Manage fees for online service bookings.' }, { key: 'event', title: 'Events', description: 'Manage fees for paid event tickets.' }];
const conditions: Record<string, string> = { all: 'All conditions', new: 'New', like_new: 'Like new', used_good: 'Used — good', used_fair: 'Used — fair' };
const dollars = (value: number) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(value / 100);
const initial = (feature: Feature): Rule => ({ id: 0, feature, collectionMethod: 'transaction', itemCondition: 'all', category: 'all', billingInterval: 'month', subscriptionCents: 0, percentageBps: 0, fixedFeeCents: 0, chargedTo: 'provider', active: false, version: 1 });
export default function PricingManager({ request }: { request: (path: string, init?: RequestInit) => Promise<any> }) {
  const [rules, setRules] = useState<Rule[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [message, setMessage] = useState('');
  const [feature, setFeature] = useState<Feature>('item'), [editing, setEditing] = useState<Rule | null>(null), [busy, setBusy] = useState(false);
  const [categories, setCategories] = useState<string[]>([]);
  const editor = useRef<HTMLDivElement>(null), createButton = useRef<HTMLButtonElement>(null);
  async function load() { setLoading(true); setError(''); try { setRules(await request('/api/v1/admin/pricing-rules')); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load pricing.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); /* Fetch the separate pricing surface only when opened. */ }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (editing) { editor.current?.scrollIntoView({ block: 'nearest' }); editor.current?.focus(); } }, [editing?.id, editing?.feature]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { let active = true; void request('/api/v1/utility/categories').then(data => { if (active) setCategories((data.categories ?? data ?? []).map((row: { name: string }) => row.name)); }).catch(() => { /* All categories is still available. */ }); return () => { active = false; }; }, [request]);
  const patch = (value: Partial<Rule>) => setEditing(row => row ? { ...row, ...value } : row);
  const close = () => { setEditing(null); createButton.current?.focus(); };
  async function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editing || busy) return;
    setBusy(true); setError(''); setMessage('');
    try {
      const saved = await request(`/api/v1/admin/pricing-rules${editing.id ? `/${editing.id}` : ''}`, { method: editing.id ? 'PATCH' : 'POST', body: JSON.stringify(editing) });
      setRules(rows => editing.id ? rows.map(row => row.id === saved.id ? saved : row) : [...rows, saved]);
      setMessage('Pricing rule saved. Existing orders keep their original fee.'); close();
    } catch (e) { setError(e instanceof Error ? e.message : 'Could not save pricing.'); } finally { setBusy(false); }
  }
  async function remove(rule: Rule) {
    if (!window.confirm('Delete this pricing rule for future checkouts? Existing orders and audit history will be preserved. Deleting the default transaction rule can stop new paid checkouts.')) return;
    setBusy(true); setError('');
    try { await request(`/api/v1/admin/pricing-rules/${rule.id}`, { method: 'DELETE', body: JSON.stringify({ version: rule.version }) }); setRules(rows => rows.filter(row => row.id !== rule.id)); setMessage('Pricing rule deleted.'); if (editing?.id === rule.id) close(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not delete pricing.'); } finally { setBusy(false); }
  }
  const duplicate = !!editing && rules.some(row => row.id !== editing.id && row.feature === editing.feature && row.collectionMethod === editing.collectionMethod && row.itemCondition === editing.itemCondition && row.category === editing.category.trim().toLowerCase() && (row.collectionMethod === 'transaction' || row.billingInterval === editing.billingInterval));
  const list = rules.filter(row => row.feature === feature);
  return <section className="admin-settings pricing-workspace">
    <div className="workspace-intro"><div><span className="panel-kicker">Revenue settings</span><h2>Platform pricing</h2><p>Create a rule once, then manage it here. Existing orders keep their agreed prices.</p></div><button className="admin-secondary" onClick={() => void load()} disabled={loading || busy}>Refresh pricing</button></div>
    <div className="workspace-tabs" role="group" aria-label="Pricing feature">{features.map(item => <button key={item.key} aria-pressed={feature === item.key} disabled={busy} onClick={() => { setFeature(item.key); setEditing(null); setError(''); }}><strong>{item.title}</strong><span>{rules.filter(row => row.feature === item.key).length} rules</span></button>)}</div>
    <div className="workspace-list-heading"><div><h3>{features.find(item => item.key === feature)?.title}</h3><p>{features.find(item => item.key === feature)?.description}</p></div><button ref={createButton} disabled={loading || busy || !!error} onClick={() => { setEditing(initial(feature)); setMessage(''); }}><span aria-hidden="true">＋ </span>Create rule</button></div>
    {feature === 'item' ? <p className="workspace-note">Item purchases currently happen outside Tivorah. Item rules define pricing but do not collect money until item checkout is available.</p> : null}
    <p className="workspace-note">Specific categories override “All categories”; within a category, an exact item condition overrides “All conditions”. Only one transaction rule applies.</p>
    <p className="workspace-note">Saving or removing the active “All categories / All conditions” transaction rate sends connected sellers a one-time notice they must acknowledge on next login.</p>
    {error ? <div className="workspace-error" role="alert">{error} <button className="admin-secondary" disabled={loading} onClick={() => void load()}>Retry loading</button></div> : null}
    <p role="status" className="workspace-feedback">{message}</p>
    {editing ? <div ref={editor} tabIndex={-1} className="pricing-editor"><form onSubmit={save} aria-busy={busy}><h3>{editing.id ? 'Edit rule' : 'New rule'}</h3><div className="pricing-fields">
      <label>Collection method<select value={editing.collectionMethod} onChange={e => patch({ collectionMethod: e.target.value as Rule['collectionMethod'], active: false, chargedTo: 'provider' })}><option value="transaction">Per transaction</option><option value="subscription">Subscription — draft</option></select></label>
      {feature === 'item' ? <label>Item condition<select value={editing.itemCondition} onChange={e => patch({ itemCondition: e.target.value })}>{Object.entries(conditions).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label> : null}
      {feature === 'item' ? <label>Category<select value={editing.category} onChange={e => patch({ category: e.target.value })}><option value="all">All categories</option>{[...new Set([...categories.map(value => value.toLowerCase()), ...(editing.category !== 'all' ? [editing.category] : [])])].map(value => <option key={value} value={value}>{value}</option>)}</select></label> : null}
      {editing.collectionMethod === 'subscription' ? <><label>Billing period<select value={editing.billingInterval} onChange={e => patch({ billingInterval: e.target.value as Rule['billingInterval'] })}><option value="month">Monthly</option><option value="year">Yearly</option></select></label><label>Subscription price (AUD)<input required type="number" min="0.01" max="100000" step="0.01" value={editing.subscriptionCents / 100} onChange={e => patch({ subscriptionCents: Math.round(Number(e.target.value) * 100) })} /></label></> : <><label>Percentage fee (%)<input required type="number" min="0" max="100" step="0.01" value={editing.percentageBps / 100} onChange={e => patch({ percentageBps: Math.round(Number(e.target.value) * 100) })} /></label><label>Fixed fee (AUD)<input required type="number" min="0" max="1000" step="0.01" value={editing.fixedFeeCents / 100} onChange={e => patch({ fixedFeeCents: Math.round(Number(e.target.value) * 100) })} /></label><label>Paid by<select value={editing.chargedTo} onChange={e => patch({ chargedTo: e.target.value as Rule['chargedTo'] })}><option value="provider">Seller / provider / organiser</option><option value="buyer">Buyer</option></select></label><label>Status<select value={editing.active ? 'active' : 'off'} onChange={e => patch({ active: e.target.value === 'active' })}><option value="off">No platform fee</option><option value="active">Charge this fee</option></select></label></>}
    </div>{editing.collectionMethod === 'subscription' ? <p className="workspace-note">Subscription checkout is not connected yet. This saves a draft rate and cannot start recurring charges.</p> : <p>On a A$100 purchase: {dollars(editing.chargedTo === 'provider' ? Math.min(10000, editing.percentageBps + editing.fixedFeeCents) : editing.percentageBps + editing.fixedFeeCents)} platform fee{!editing.active ? ' (currently switched off)' : ''}.</p>}
    {duplicate ? <p role="alert" className="workspace-error">A rule already covers this collection method and scope. Edit that rule instead.</p> : null}
    <div className="workspace-actions"><button disabled={busy || duplicate}>{busy ? 'Saving…' : 'Save rule'}</button><button className="admin-secondary" type="button" disabled={busy} onClick={close}>Cancel</button></div></form></div> : null}
    {loading ? <p role="status">Loading pricing rules…</p> : !list.length ? <div className="workspace-empty"><h3>No rules for this feature</h3><p>Create a rule to define how this feature is priced.</p></div> : <div className="pricing-rule-list">{list.map(rule => <article key={rule.id} className="pricing-rule"><div><span className="workspace-status">{rule.collectionMethod === 'subscription' ? 'Subscription draft' : rule.active ? 'Active transaction fee' : 'No platform fee'}</span><h4>{rule.collectionMethod === 'subscription' ? `${dollars(rule.subscriptionCents)} / ${rule.billingInterval}` : `${rule.percentageBps / 100}% + ${dollars(rule.fixedFeeCents)}`}</h4><p>{rule.category === 'all' ? 'All categories' : rule.category}{feature === 'item' ? ` · ${conditions[rule.itemCondition]}` : ''}</p><small>{rule.collectionMethod === 'transaction' ? `Paid by ${rule.chargedTo === 'buyer' ? 'buyer' : 'seller / provider / organiser'} · ` : ''}Version {rule.version}</small></div><div className="workspace-actions"><button className="admin-secondary" disabled={busy} onClick={() => { setEditing({ ...rule }); setError(''); }}>Edit</button><button className="admin-danger" disabled={busy} onClick={() => void remove(rule)}>Delete</button></div></article>)}</div>}
  </section>;
}
